### PR TITLE
 Fix the `retryTimeout` option in `runAsyncChain`, inline `testDelayed()` with the main module

### PR DESCRIPTION
**Pull request by dpikhulya**
Contains the following:
- The `retryTimeout` option in `runAsyncChain` calls wasn't taken into account
- Moved the `testDelayed()` function from its own module to the main `spine-test-helpers.js` module. 
- Added a Travis build with a basic test that checks `NodePredicates` as a starting point for writing tests.
   
   It now became possible because `spine-test-helpers` is now a `.js` file instead of an `.html` file. Having it in `.html` file wasn't suitable for `testDelayed()`, because it had to be available on the page before HTML Imports polyfill loaded it (e.g. in Mozilla).
- Increased package version number to `0.4.0` since moving an API is a backwards-incompatible change.

### CODE REVIEW

**Review by armiol — APPROVED** [review]
@dpikhulya LGTM.

We need to have at least some tests for this library. 
In Spine we have `testlib` artifact, and its code is covered with tests. So something similar here is my suggestion.

**Comment by armiol** [comment]
Oh, and a Travis build.

**Comment by dpikhulya** [comment]
Yep, totally agree that tests are needed, there's even a ticket for this [here](https://github.com/SpineElements/spine-test-helpers/issues/6). I'll try to fit this (possibly in parts) along with upcoming tasks that involve using this module. 

As to the Travis build, seems that we'll be able to add it only after we have some tests.

**Comment by dpikhulya** [comment]
Added the build with a basic test as a starting point.

**Pull request merged**
